# Generated by Django 3.0.7 on 2020-06-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='movies/pictures'),
        ),
    ]
